/* eslint-disable max-len */
/* eslint-disable prettier/prettier */
const MESSAGES = {
  USER_SIGNUP_COMPLETE:'User has been registered successfully!',
  USER_ALREADY_EXIT:'User already exited with given mobile no.',
  NO_USER_FOUND:"No user found with given credentials",
  INVALID_TOKEN: 'Token Invalid!',
  DATA_FOUND: 'Data Found!',
  NO_DATA_FOUND: 'No Data Found!',
  LOGIN_SUCCESS: 'Login successful!',
  LOGOUT_SUCCESS: 'Logged out successful!',
  SET_PASS: 'Set your password first!',
  IN_ACTIVATE_STUDENT: 'Your account is inactive.',
  IN_ACTIVATE_STAFF: 'Your account is inactive.',
  ACTIVATED: 'Student activated successfully.',
  IN_ACTIVATED: 'Student inactivated successfully.',
  ACTIVATED_STAFF: 'Staff activated successfully.',
  IN_ACTIVATED_STAFF: 'Staff inactivated successfully.',
  LOGIN_FAILED: 'Login Failed!',
  ALREADY_EXISTS: 'Record already exists in our records.',
  TEMP_ALREADY_EXISTS: 'Template with same name already exists.',
  EMAIL_ALREADY_EXISTS:
    'This email id is already associated with another user.',
  STUDENT_EMAIL_ALREADY_EXISTS: 'Student email already exist in our records !',
  NOT_EXISTS: 'Account does not exist in our records !',
  SOMETHING_WRONG: 'Something went wrong!',
  INVALID_EMAIL: 'You have entered an email is not exist in our records.',
  INVALID_PASSWORD:
    'You have entered a password that does not match your email.',
  INVALID_CRED: 'You have entered an invalid email address or password!',
  INVALID_MAIL: 'You have entered an invalid email address!',
  OTP_SENT: 'OTP has been sent to your registered email!',
  OTP_NOT_SENT: 'OTP send failed!',
  INVALID_OTP: 'You have entered an invalid OTP!',
  OTP_VERIFY: 'OTP verified successfully!',
  PASSWORD_VERIFIED: 'Password updated successfully!',
  BAD_REQUEST: 'Invalid request!',
  VALID_USER: 'Valid User',
  USER_TYPE_NOT_ACTIVE: 'User type not active!',
  VALIDATION_ERROR: 'Validation error!',
  DATA_NOT_CREATED: 'Record has not been created!',
  DATA_NOT_UPDATED: 'Record has not been updated!',
  DATA_UPDATED: 'Record updated successfully!',
  DATA_DELETED: 'Record deleted successfully!',
  DATA_NOT_DELETED: 'Could not delete record!',
  UNIQUE_ID_ALREADY_EXISTS: 'Uniques id is already in exists in our records.',
  STUDENT_USER_TYPE_NOT_FOUND: 'Student user type has not been found.',
  PARENT_USER_TYPE_NOT_FOUND: 'Parent user type has not been found.',
  USER_TYPE_NOT_FOUND: 'User type has not been found.',
  STAFFS_NOT_FOUND: 'Staff details has not been found.',
  STAFFS_ADDED: 'Staff details has been saved successfully.',
  STUDENTS_NOT_FOUND: 'Students has not been found.',
  REPORTCARD_STUDENTS_NOT_FOUND: 'Students not found.',
  STUDENTS_ADDED: 'Students has been added successfully.',
  STUDENTS_INVITED: 'Students has been invited successfully.',
  STAFF_INVITED: 'Staff has been invited successfully.',
  RECOVERY_EMAIL_SENT: 'Recovery link has been sent to the registered Email Id',
  FILE_REQUIRED: 'Input file is required!',
  FILE_UPLOADED: 'File uploaded successfully!',
  FILE_NOT_UPLOADED: 'Error uploading file!',
  EXCEL_GENERATION_FAILED: 'Excel generation failed',
  EXCEL_UPLOAD_FAILED: 'Excel upload failed',
  DATA_EXISTS: 'Record already exists',
  PASSWORD_ALREADY_SET: 'Password already set for this account!',
  INSTITUTION_NOT_FOUND: 'Institution has not been found!',
  INSTITUTION_ALREADY_EXIST: 'Institution Name already exists!',
  NOT_UNIQUE: 'Already exists with same value!',
  ALREADY_SUBMITTED_RESPONSE: 'You have already submitted a feedback response.',
  INVALID_TOKEN: 'Token Invalid!',
  DATA_FOUND: 'Data Found!',
  NO_DATA_FOUND: 'No Data Found!',
  LOGIN_SUCCESS: 'Login successful!',
  SET_PASS_SUCCESS: 'Password set successfully!',
  LOGOUT_SUCCESS: 'Logged out successful!',
  SET_PASS: 'Set your password first!',
  LOGIN_FAILED: 'Login Failed!',
  ALREADY_EXISTS: 'Record already exists in our records.',
  EMAIL_ALREADY_EXISTS:
    'This email id is already associated with another user.',
  MOBILENO_ALREADY_EXISTS:
    'This mobileNo is already associated with another user',
  CLASSMANAGEMENT_ALREADY_EXISTS:
    'This staff is already associated with another class in class management',
  SOMETHING_WRONG: 'Something went wrong!',
  INVALID_PASSWORD:
    'You have entered a password that does not match your email.',
  INVALID_CRED: 'You have entered an invalid mobile address or password!',
  INVALID_MAIL: 'You have entered an invalid email address!',
  INVALID_MOBILE: 'You have entered an invalid mobile no!',
  OTP_SENT: 'OTP has been sent to your registered email!',
  OTP_SENT_MOBILE: 'OTP hase been sent to your registered mobile number!',
  OTP_NOT_SENT: 'OTP send failed!',
  INVALID_OTP: 'You have entered an invalid OTP!',
  OTP_VERIFY: 'OTP verified successfully!',
  PASSWORD_VERIFIED: 'Password updated successfully!',
  BAD_REQUEST: 'Invalid request!',
  VALID_USER: 'Valid User',
  USER_TYPE_NOT_ACTIVE: 'User type not active!',
  VALIDATION_ERROR: 'Validation error!',
  VALIDATION_SUCCESSFULL: 'Validation success!',
  DATA_CREATED: 'Record created successfully!',
  DATA_NOT_CREATED: 'Record has not been created!',
  DATA_NOT_CREATED: 'Record has not been created!',
  SOME_DATA_NOT_UPDATED: 'Some records has not been created!',
  DATA_UPDATED: 'Record updated successfully!',
  UNIQUE_ID_ALREADY_EXISTS: 'Same unique id exists in the batch already.',
  EXCEL_UPLOAD_FAILED: 'Excel upload failed',
  DATA_EXISTS: 'Record already exists',
  PASSWORD_ALREADY_SET: 'Password already set for this account!',
  INSTITUTION_NOT_FOUND: 'Institution has not been found!',
  NOT_UNIQUE: 'Already exists with same value!',
  ALREADY_SUBMITTED_RESPONSE: 'You have already submitted a feedback response.',
  FEEDBACK_FORM_NOT_FOUND: 'Feedback form is not exist in our records',
  LIKE_DOUBT: 'Doubt Liked',
  UNLIKE_DOUBT: 'Doubt Unliked',
  RESOLVE_DOUBT: 'Doubt resolved successfully',
  UNRESOLVE_DOUBT: 'Response unmark successfully',
  STAFF_UNIQUE_EMPLOYEE_CODE:
    'This employee code already belongs to another member.',
  PROFILE_PIC_DELETED: 'Profile picture has been deleted successfully.',
  VALID_EMPID: 'Valid employee code',
  TEMPLATE_NOT_FOUND: 'Template not found',
  CAPACITY: 'You already have greater capacity',
  PENDING_CAPACITY: 'You already have a pending request',
  ACCOUNT_DEACTIVATED: 'Your account has been deactivated',
  INSTITUTE_IS_NOT_ACTIVE:
    'Please contact your institution since this credential is inactive',
  DATA_VALIDATED: 'Data validated successfully.',
  TRANSACTION_SUCCESS: 'Payment Done Successfully!',
  DATA_NOT_VALIDATED: 'Data not validated successfully.',
  MAX_QUESTION_LIMIT_EXCEEDED: 'Maximum question limit exceeded',
  NO_OF_ROWS_NOT_MATCHING: 'The number of rows are not exact',
  INVALID_ZIP_FILE: 'Invalid zip file',
  FAQ_CATEGORY_NOT_FOUND: 'FAQ category deos not exists',
  CANNOT_COMIT: 'Cannot Commit, please migrate all Students',
  DUPLICATE_PHONE_NUMBER: 'Added Phone Number already exixts',
  DUPLICATE_EMAIL: 'Added Email address already exixts',
  DUPLICATE_WEBSITE: 'Added website already exixts',
  TIMEPERIOD_BYPASS: 'Timeperiod cannot be bypassed',
  OVERLAP_HOLIDAY: 'Day is already marked as holiday',
  ARCHIVE_ONGOING: 'Access Blocked as Archiving in Progress',
  TRANSACTION_FAILED: 'Transaction failed',
  TRANSACTION_TIMED_OUT: 'Transaction timed out, awaiting Confirmation.',
  NO_TRANSACTION_FOUND: 'No such Transaction found',
  INVALID_KEY: 'Please provide valid key',
  NO_DELETE_COMMITTED: 'Cannot delete committed schedule',
  NO_DELETE_PAYMENT_EXISTS: 'Cannot delete schedule, Payment already exists',
  TITLE_ALREADY_EXISTS: 'Title already exists',
  DESCRIPTION_ALREADY_EXISTS: 'Description already exists',
  STUDENT_ALREADY_ISSUED_BOOK: 'Book already issued to student',

  UNAUTHORISED: 'You do not have permission to perform this action!',
  GENERAL_ERROR: 'Some error has been occured !',
  VALIDATION: {
    OTP: 'Otp should be minimum 6 digit',
    PASSWORD: 'Password should be minimum 6 character',
    DESC: 'Description should be maximum 300 character',
    ANNOUNCEMENT_DESC: 'Description should be maximum 1500 character'
  },
  Generalstatus: {
    PENDING: 'Pending',
    APPROVED: 'Approved',
    REJECTED: 'Rejected'
  },
  SOME_DATA_MISSING:'Some data missing or wrong from payload',
  PAYMENT_PENDING:'Payment is pending for this given id.',
  ORDER_PICKUP_SUCCESS: 'Item Order(s) has been confirmed successfully.',
  ORDER_REJECTED: 'Item orders has been rejected.',
  IS_ASSIGN_POSSIBLE:'Please select some students or items to assign the student(s).',
  SELECT_PROPER_NO_OF_STUDENT:'Please select proper no of students.',
  VALID_ITEM_ID:'Please provide valid item id.',
  ITEM_ASSIGN_TO_STUDENT:'Item has/have been assign to student(s) successfully.'
};

export default MESSAGES;

